source 'https://rubygems.org'

ruby File.read('.ruby-version').strip

gem 'erubis'
gem 'mysql2'
gem 'mysql2-cs-bind'
gem 'sinatra'
gem 'unicorn'

gem 'dalli'

gem 'stackprof'

group :development do
  gem 'foreman'
  gem 'sinatra-contrib', require: nil
end
